### PR TITLE
Add LGPL license

### PR DESCRIPTION
**Pull request by mbutterick**

### CODE REVIEW

**Comment by jbclements** [comment]
Danny ( @dyoo ) : It seems really silly that pkgs.racket-lang.org points to this repo instead of directly to yours. Wouldn't it make more sense to point the server at your repo?

**Comment by dyoo** [comment]
The problem though is that I'm currently not in a position to rapidly respond or contribute due to my current employment.  I have to admit that I can not be a responsible maintainer at the moment.

**Comment by mbutterick** [comment]
Since that’s the case, and the LGPL license is now in place, this repo should arguably be recognized as the canonical one. There are a few references in the docs to `dyoo/ragg` but I could PR those easily.

**Comment by jbclements** [comment]
I'm happy with any of these solutions. With respect to the "rapidly respond or contribute" metric, I'd say that I'm even less likely than Danny to contribute—I don't even know what the code looks like—but it's at least conceivable that I might respond more quickly. It strikes me that I might "spread the load" by adding you, @mbutterick , as one of the authors listed at pkgs.racket-lang.org, so that you could simply point the package at a different repo if needed. Would you object to my adding you as a package author? (Danny and I are already listed.)

**Comment by jbclements** [comment]
In fact... forget the formalities: I just added you as an author. I'll remove you, if you ask me to.

**Comment by mbutterick** [comment]
Fine. FWIW I’ve created a fork of `ragg` called [`beautiful-racket-ragg`](https://github.com/mbutterick/beautiful-racket/tree/master/beautiful-racket-ragg) so I can make some changes for my project (if I come up with anything worthwhile I’ll send a PR this way)

**Comment by mbutterick** [comment]
(PS I see on the package server that I caused a conflict between the packages by not changing the name of the main documentation file; I just pushed a fix)

**Comment by mbutterick** [comment]
Please excuse my abuse of this thread to ask an unrelated question (since issues are deactivated for this repo). 

The docs say: “A future version of ragg will probably support annotations on patterns so that they can be omitted or transformed in the parser output.”

If I make an improvement to `ragg`, this would be it. Even with macros, parse-tree-post-processing is a chore and a bore, so in-parser annotations would be a big help.

The question: What is the best-of-breed approach for doing this? Are `yacc` style annotations still favored? Or is there a better notation? I’m not soliciting anyone to do the heavy lifting, I’m just asking for models to study.

**Comment by dyoo** [comment]
Offhand, instaparser might be worth investigating.
https://github.com/Engelberg/instaparse.  Mark uses angle brackets to
indicate parts that should be elicited.

**Comment by mbutterick** [comment]
Thanks. Cute idea. I hacked the angle-bracket operator into my `br/ragg` branch and it works nicely. (I can imagine more elaborate systems of annotation but being able to filter & splice elements covers 80% of what I've found a need for.)

But, this raises a general policy issue about the stewardship of `ragg`. I would PR the angle brackets into this main repo. But that would break backward compatibility ([for instance](https://github.com/jbclements/ragg/blob/master/ragg/examples/bnf.rkt)). I know that BC is a high virtue in Racketland. Does that imply that basically we will be maintaining this repo for bugfixes only, and the rest should go into a new `ragg2`?

**Comment by jbclements** [comment]
I hate to say it, but I don't really have a strong opinion on this.

**Comment by mbutterick** [comment]
I suppose I can answer my own question. Aside from Racketland package-maintenance ethics, @dyoo may someday wish to retake the reins of `ragg`. At that point, the repo should not be in a state of backward-incompatibility, which is an irreversible choice (nor should it have induced reliance on new features). That is the whole point of having forks (in fact I will rename mine to make the divergence more obvious). In this repo, the goal will be groundskeeping.

**Comment by mbutterick** [comment]
FWIW here are the refinements I’ve made to [parse-tree processing](https://github.com/mbutterick/beautiful-racket/blob/master/beautiful-racket/br/demo/txtadv/parser.rkt) inside `ragg` (or `brag` as I've called my fork). 

For terminals or nonterminals, the `/` prefix means *omit*: used on the right side = omit that element; on the left = omit only the rule name. Additionally for nonterminals, the `@` prefix means *splice*: used on the right side = splice this particular instance of the nonterminal; on the left = splice it everywhere it appears.

With these two operations, I’m able to squish the parse tree into a shape that fits more naturally with macro pattern matching (especially ellipses). 

For instance, this recursive rule leaves an indefinitely nested structure in the parse tree (the `/` deletes the commas):

```
verb-list : verb [/"," verb-list]
```

Whereas with `@`, the rule will generate a flat list:

```
@verb-list : verb [/"," verb-list]
```

Another bugaboo in Racket syntax patterns is matching alternating arguments:

```
everywhere-section : title [id desc]+
```

Now these can be neatly packaged into their own sublist (which can be matched later with an ellipsis):

```
everywhere-section : title id-desc+
/id-desc : id desc
```

**Comment by dyoo** [comment]
Very cool.

Sorry for very late response; missed this in my inbox.

**Pull request merged**
